### ISSUE TITLE
I cannot compile this program

### ISSUE THREAD

**Issue by TaeYunAhn** [ethan0905/so_long-new-version#1]
when I use "make all" the terminal said "./so_long.h:28:11: fatal error: './mlx/mlx.h' file not found"
<img width="631" alt="Screen Shot 2022-02-08 at 8 13 17 PM" src="https://user-images.githubusercontent.com/80814896/152976068-ac776547-7ec3-409d-b3de-bd8aab920f68.png">

**Comment by ethan0905** [comment]
Hey hello, of course that's a normal error. In order to make the project work, you should clone this repo and replace it with the actual empty folder called "mlx". Here is the link to the repository : https://github.com/42Paris/minilibx-linux. Hope that helped you :)

Edit: just added the mlx files to the repo, now you simply need to compile it

**Comment by TaeYunAhn** [comment]
oh, I got it now thanks a lot!!

**Comment by ethan0905** [comment]
Resolved
